[package]
name = "rust_provider"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = {version="1.0.209", features = ["derive"] }
axum = "0.7.5"
lazy_static = "1.5.0"